mysite/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gaestd_py_django_local_static]
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# [END gaestd_py_django_local_static]

polls/urls.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login', views.login, name='login'),
    path('create', views.create, name='create')
]

polls/models.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.http import HttpResponse, HttpResponseRedirect # noqa: 401
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.decorators import csrf
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'

class DetailView(generic.ListView):
    template_name = 'polls/detail.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id,))
        )

def login(request):
    try:
        username = request.POST['uname']
        password = request.POST['psw']
    except:
        return HttpResponseRedirect(reverse(request.META.get('HTTP_REFERER'), args={'message': "Invalid credentials"}))
    else:
       
        user = authenticate(username=username, password=password)
        if user is not None:
            return render(request, 'polls/detail.html', {
                'question': request.POST['uname'],
                'latest_question_list': Question.objects.order_by('-pub_date')
            })
        else:
            return render(request, 'polls/index.html', {
                'message': 'ユーザ名もしくはパスワードが間違いました'
            })
            

def create(request):
    try:
        username = request.POST['uname']
        email = request.POST['email']
        password = request.POST['psw']
        user = User.objects.create_user(username, email, password)
        user.save()
    except:
        return render(request, 'polls/index.html', {
            'message': 'That username is already taken, try another one'
        })
    else:
        user = authenticate(username=username, password=password)
        if user is not None:
            return render(request, 'polls/detail.html', {
                'question': request.POST['uname']
            })
        else:
            return render(request, 'polls/index.html', {
                'message': 'That username is already taken, try another one'
            })

polls/templates/polls/detail.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<head>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    
    <script type="text/javascript">
        $(document).ready(function () {
    
            $('.logoutButton').click(function () {
                
            })    
        })
    </script>
</head>

<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
            <span style="font-size: 18pt">螢出版情報管理システム</span>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row" style="padding: 20px;">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <form method="get" action="/">
                    <button id="logoutButton" type="submit" class="btn btn-secondary" size="lg" style="margin: 10px; padding: 10px;">ログアウト</button>
                </form>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <span style="color: green; font-weight: bolder;">ようこそ　{{ question }}</b>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row" style="padding: 20px;">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
            <span style="font-size: 12pt">校正・校了情報は下記のとおりです</span>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% if latest_question_list %}
    <div class="row" style="padding: 20px;">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <ul>
                    {% for question in latest_question_list %}
                        <li>{{ question.question_text }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% endif %}
</div>

polls/templates/polls/index.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

{% load static %}

{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<head>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>


<script type="text/javascript">
    $(document).ready(function () {
  
    })
  </script>
</head>

<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
            <span style="font-size: 18pt">螢出版情報管理システム</span>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% if message %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <span style="color: red; font-weight: bolder;">{{ message }}</b>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    {% endif %}
</div>



<div class="container">
    <form class="loginForm" action="{% url 'polls:login' %}" method="post">
    {% csrf_token %}
    <div class="row" style="padding: 20px;">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <label for="uname"><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="uname" required>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="psw" required>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row" style="padding: 20px;">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="text-center">
                <button id="loginButton" type="submit" class="btn btn-secondary" size="lg" style="margin: 10px; padding: 10px;">ログイン</button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
    </form>
</div>

polls/templates/polls/results.html
{% comment %}
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
{% endcomment %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>